### ISSUE TITLE
ImportError: No module named cobertura_clover_transform.converter`

### ISSUE THREAD

**Issue by hons82** [cwacek/cobertura-clover-transform#11]
I've installed it and now I get this error:

`$ cobertura-clover-transform /Users/htribus/bamboo-agent-home/xml-data/build-dir/STIOS-CON-JOB1/target/reports/coverage/cobertura.xml 
Traceback (most recent call last):
  File "/usr/local/bin/cobertura-clover-transform", line 9, in <module>
    load_entry_point('cobertura-clover-transform==1.1.4.post1', 'console_scripts', 'cobertura-clover-transform')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named cobertura_clover_transform.converter`

Have you seen that already?

**Comment by cwacek** [comment]
I have not seen that before. It looks like the installation didn't work quite right. What do you get if you do the following?

```
$ pip show cobertura-clover-transform
$ python
> import cobertura_clover_transform
```
